apiVersion: kro.run/v1alpha1
kind: TicTacToeApp
metadata:
  name: tictactoe-staging
spec:
  environment: staging
  imageTag: "8d93bab"
  replicas: 2
  backendReplicas: 2
  cpuRequest: "50m"
  cpuLimit: "200m"
  memoryRequest: "16Mi"
  memoryLimit: "64Mi"
  albId: "app/k8s-tictacto-tictacto-56b83df6f7/0cc7d8fbc1f5c80e"
  albUrl: "http://k8s-tictacto-tictacto-56b83df6f7-1529768459.ap-northeast-2.elb.amazonaws.com"
