apiVersion: kro.run/v1alpha1
kind: TicTacToeApp
metadata:
  name: tictactoe-prod
spec:
  environment: prod
  imageTag: 336dc2a
  replicas: 3
  backendReplicas: 3
  cpuRequest: "100m"
  cpuLimit: "500m"
  memoryRequest: "32Mi"
  memoryLimit: "128Mi"
  albId: "app/k8s-tictacto-tictacto-07fc5efb78/f772a119281e76d4"
