apiVersion: kro.run/v1alpha1
kind: TicTacToeApp
metadata:
  name: tictactoe-prod
spec:
  environment: prod
  imageTag: 2c6f989
  replicas: 3
  backendReplicas: 3
  cpuRequest: "100m"
  cpuLimit: "500m"
  memoryRequest: "32Mi"
  memoryLimit: "128Mi"
  albId: "app/k8s-tictacto-tictacto-07fc5efb78/f0f2f2f2f2f2f2f2"
  albUrl: "http://k8s-tictacto-tictacto-07fc5efb78-1765375059.ap-northeast-2.elb.amazonaws.com"
