apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- networkpolicy.yaml
- pdb.yaml
- nginx-config.yaml
- ingress.yaml
- backend/
# Webhook test Fri 28 Nov 2025 17:33:36 PST
