apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tictactoe-dev
resources:
- ../../base
- namespace.yaml
- grafana/dashboard.yaml
- grafana/business-dashboard.yaml
images:
- name: ghcr.io/pnz1990/tictactoe-k8s
  newName: ghcr.io/pnz1990/tictactoe-k8s
  newTag: "bb0bfcd"
- name: ghcr.io/pnz1990/tictactoe-k8s-backend
  newName: ghcr.io/pnz1990/tictactoe-k8s-backend
  newTag: "bb0bfcd"
patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: tictactoe
