apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tictactoe-staging
resources:
- ../../base
- namespace.yaml
- grafana/dashboard.yaml
- grafana/business-dashboard.yaml
images:
- name: ghcr.io/pnz1990/tictactoe-k8s
  newTag: staging
- name: ghcr.io/pnz1990/tictactoe-k8s-backend
  newTag: staging
patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: 50m
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: 200m
  target:
    kind: Deployment
    name: tictactoe
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
  target:
    kind: Deployment
    name: tictactoe-backend
