apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencost
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://opencost.github.io/opencost-helm-chart
    chart: opencost
    targetRevision: 1.42.0
    helm:
      values: |
        opencost:
          exporter:
            defaultClusterId: unique-lofi-goose
            aws:
              spot_data_region: ap-northeast-2
          prometheus:
            internal:
              enabled: false
            external:
              enabled: true
              url: https://aps-workspaces.ap-northeast-2.amazonaws.com/workspaces/ws-62f6ab4b-6a1c-4971-806e-dee13a1e1e95
          ui:
            enabled: true
  destination:
    server: arn:aws:eks:ap-northeast-2:569190534191:cluster/unique-lofi-goose
    namespace: opencost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
