apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencost
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://opencost.github.io/opencost-helm-chart
    chart: opencost
    targetRevision: 2.4.1
    helm:
      values: |
        opencost:
          exporter:
            defaultClusterId: unique-lofi-goose
            aws:
              spot_data_region: ap-northeast-2
          prometheus:
            internal:
              enabled: true
              serviceName: opencost-prometheus-server
              namespaceName: opencost
              port: 80
          ui:
            enabled: true
          cloudCost:
            enabled: true
            monthToDateInterval: 6
            refreshRateHours: 6
            queryWindowDays: 7
        serviceAccount:
          create: true
          name: opencost
  destination:
    server: arn:aws:eks:ap-northeast-2:569190534191:cluster/unique-lofi-goose
    namespace: opencost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
